implement GET+POST `cluster/{cluster}/requests`
RedHatInsights/insights-results-smart-proxy pull request #1055
Opened 2023-06-05 15:55 UTC by Bee-lee

# Description
- implement GET `cluster/{cluster}/requests`
- implement POST `cluster/{cluster}/requests`
- add missing operationId for POST `cluster/{cluster}/requests`
- Redis function to get details of Requests uses Redis pipelines so that our client only makes 1 request to the server to avoid multiple round trips
- because of ^ point, Redis is now a direct dependency

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Unit tests (no changes in the code)
- REST API tests

## Testing steps
local testing with real Redis with data according to spec doc

## Checklist
* [ ] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

2023-06-05 16:13 UTC, Bee-lee commented
/retest

2023-06-06 05:08 UTC, juandspy approved these changes

2023-06-06 05:27 UTC, tisnik requested changes
LGTM in overall, just one comment.

2023-06-06 05:27 UTC, tisnik commented on server/router_utils.go
> +	var requestList []string
you can pre-allocate by `make`

2023-06-06 09:13 UTC, Bee-lee commented on server/router_utils.go
> +	var requestList []string
done

2023-06-06 09:26 UTC, tisnik approved these changes
LGTM

2023-06-06 10:01 UTC, Bee-lee commented
/retest

2023-06-06 10:09 UTC, Bee-lee commented
/retest

2023-06-06 10:51 UTC, Bee-lee commented
/retest

2023-06-06 13:50 UTC, Bee-lee commented
/retest

2023-06-06 14:22 UTC, Bee-lee commented
/retest

2023-06-06 14:49 UTC, Bee-lee commented
/retest

2023-06-06 15:19 UTC, Bee-lee commented
/retest

2023-06-06 16:02 UTC, Bee-lee commented
/retest

2023-06-06 19:11 UTC, merged