[CCXDEV-6474] Update go image version to 1.16
RedHatInsights/insights-results-smart-proxy pull request #721
Opened 2021-11-18 09:02 UTC by juandspy

# Description

Use [RHEL image](https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666?container-tabs=overview) with `go 1.16.7` version.

Fixes [CCXDEV-6474](https://issues.redhat.com/browse/CCXDEV-6474).

## Type of change

- Bump-up dependent library (no changes in the code)

## Testing steps

## Checklist
* [x] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

2021-11-18 09:42 UTC, joselsegura requested changes

2021-11-18 09:42 UTC, joselsegura commented on Dockerfile
> +FROM registry.redhat.io/rhel8/go-toolset:1.16.7 AS builder
I would prefer to don't stick to a minor version, just a major one (1.16 instead of 1.16.X)

2021-11-19 11:40 UTC, tisnik approved these changes
LGTM

2021-11-19 16:25 UTC, joselsegura approved these changes

2021-11-19 16:31 UTC, merged